version: "3.3"

services:
  db:
    image: mysql:8
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - ${PWD}/mysql_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-log-bin
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  backend:
    image: quarkus/corso-quarkus-jvm
    ports:
      - "8080:8080"
    restart: unless-stopped